"""015_property_operational_fields

Revision ID: 1bf0ed7491fa
Revises: 656cee3e984b
Create Date: 2026-03-11 14:03:57.231403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf0ed7491fa'
down_revision: Union[str, Sequence[str], None] = '656cee3e984b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('check_in_time', sa.String(length=20), nullable=True))
    op.add_column('properties', sa.Column('check_out_time', sa.String(length=20), nullable=True))
    op.add_column('properties', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('properties', sa.Column('groups', sa.JSON(), nullable=True))
    op.add_column('properties', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('properties', sa.Column('allow_overbooking', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('properties', sa.Column('stop_auto_sync', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'stop_auto_sync')
    op.drop_column('properties', 'allow_overbooking')
    op.drop_column('properties', 'is_active')
    op.drop_column('properties', 'groups')
    op.drop_column('properties', 'tags')
    op.drop_column('properties', 'check_out_time')
    op.drop_column('properties', 'check_in_time')
    # ### end Alembic commands ###
