"""add missing property columns

Revision ID: 656cee3e984b
Revises: 014
Create Date: 2026-03-11 13:32:50.498996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '656cee3e984b'
down_revision: Union[str, Sequence[str], None] = '014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bank_transactions_transaction_id'), table_name='bank_transactions')
    op.create_unique_constraint(None, 'bank_transactions', ['transaction_id'])
    op.drop_index(op.f('ix_booking_audit_booking_id'), table_name='booking_audit_log')
    op.create_index(op.f('ix_booking_audit_log_booking_id'), 'booking_audit_log', ['booking_id'], unique=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bookings_guest_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.alter_column('communication_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('communication_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_custom_field_values_entity'), table_name='custom_field_values')
    op.create_index(op.f('ix_custom_field_values_entity_id'), 'custom_field_values', ['entity_id'], unique=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('guidebooks_property_id_key'), 'guidebooks', type_='unique')
    op.alter_column('import_runs', 'imported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('loans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_night_audit_property_id'), table_name='night_audit_log')
    op.create_index(op.f('ix_night_audit_log_property_id'), 'night_audit_log', ['property_id'], unique=False)
    op.drop_constraint(op.f('pricing_rules_property_id_key'), 'pricing_rules', type_='unique')
    op.drop_index(op.f('ix_pricing_rules_property_id'), table_name='pricing_rules')
    op.create_index(op.f('ix_pricing_rules_property_id'), 'pricing_rules', ['property_id'], unique=True)
    op.create_unique_constraint('uq_pricing_rules_property', 'pricing_rules', ['property_id'])
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('properties', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_rate_plans_room_type_id'), 'rate_plans', ['room_type_id'], unique=False)
    op.alter_column('reconciliation_matches', 'matched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tax_types_property_id'), 'tax_types', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_types_property_id'), table_name='tax_types')
    op.alter_column('reconciliation_matches', 'matched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_rate_plans_room_type_id'), table_name='rate_plans')
    op.alter_column('properties', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_pricing_rules_property', 'pricing_rules', type_='unique')
    op.drop_index(op.f('ix_pricing_rules_property_id'), table_name='pricing_rules')
    op.create_index(op.f('ix_pricing_rules_property_id'), 'pricing_rules', ['property_id'], unique=False)
    op.create_unique_constraint(op.f('pricing_rules_property_id_key'), 'pricing_rules', ['property_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_night_audit_log_property_id'), table_name='night_audit_log')
    op.create_index(op.f('ix_night_audit_property_id'), 'night_audit_log', ['property_id'], unique=False)
    op.alter_column('loans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_runs', 'imported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('guidebooks_property_id_key'), 'guidebooks', ['property_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_custom_field_values_entity_id'), table_name='custom_field_values')
    op.create_index(op.f('ix_custom_field_values_entity'), 'custom_field_values', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('communication_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('communication_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_booking_audit_log_booking_id'), table_name='booking_audit_log')
    op.create_index(op.f('ix_booking_audit_booking_id'), 'booking_audit_log', ['booking_id'], unique=False)
    op.drop_constraint(None, 'bank_transactions', type_='unique')
    op.create_index(op.f('ix_bank_transactions_transaction_id'), 'bank_transactions', ['transaction_id'], unique=True)
    op.alter_column('bank_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
